@startuml

'Stereotyped classes
class RequestPayment <<ProcessingTask>> {
  logged : false
}

class InformationSystem <<InformationSystem>> {
  confidentiality: bool
  integrity: bool
  availability: bool
  resilient: bool
  pseudonymity: bool
  data_minimization: bool
  redundancies: bool
  tested: bool
}
note bottom #red: class InformationSystem not instantiated

'class DPIA <<DPIA>> {
'  required: ER bool
'}

'class DataBreach <<DataBreach>> {
'  has_occurred: ER bool
'}

'ER and artifact to be refined
'class ThirdCountryDataTransfer {
  'is_required: ER bool
'}

class TechnicalMeasures <<TechnicalMeasures>> {
  stereotype: GENERIC_STEREOTYPE
  category: TECHNOLOGY_CATEGORY
}
note bottom #red: class TechnicalMeasures not instantiated

class SpecialPurpose <<NotRequired>> {
 consent: CLASS consent
 employment_purpose: bool
 social_purpose: bool
 vital_interest: bool
 nonprofit_body: bool
 public_from_subject: bool
 legal_claim: bool
 public_interest: bool
 preventive_medicine: bool
 occupational_medicine: bool
 public_health: bool
 archiving: bool
 statistical_purposes: bool
}

class Purpose <<Purpose>> {
  consent: CLASS consent
  contract_performance: bool
  controller_legal_obligation: bool
  vital_interest_protection: bool
  public_interest: bool
  legitimate_interest: bool
}
note bottom #red: class Purpose not instantiated

class FilingSystem <<NotRequired>> {
    data_storage: bool
    storage_limited: bool
}

class PaymentInfo <<PersonalData>> {
  category: GENERAL
}

class Consent {
  is_collected: bool
}
note bottom #red: class Consent not instantiated

class Tollgate <<Controller>> {
  is_processor: true
}

class DataSubject <<DataSubject>> {
  is_minor : bool  
}

class DataHandler {
}

class Bank <<Recipient>> {
}

class ThirdParty <<NotRequired>> {
}

class Processor <<NotRequired>> {
}

'Artifact classes

'class DPIAReport <<Artifact>> {
' activity_description: bool
'  necessity_assessment: bool
'  proportionality_assessment: bool
'  risk_mitigation: bool
'}

'class DataBreachNotification <<Artifact>> {
'  description: bool
'  DPO_info: bool
'  consequences: bool
'  measures_taken: bool
'}

class ProcessingLog <<Artifact>> {
  to_be_filled
}
note bottom #red: artifact ProcessingLog not instantiated
  
class ConsentAgreement <<Artifact>> {
  clear_purpose: bool
  unambiguous: bool
  affirmative_action: bool
  distinguishable: bool
  specific: bool
  withdrawable: bool
  freely_given: bool
}
note bottom #red: artifact ConsentAgreement not instantiated

'Styles

skinparam class {
  BackgroundColor<<Artifact>> PaleGreen
  ArrowColor<<Artifact>> SeaGreen
  BorderColor<<Artifact>> SpringGreen
  BackGroundColor<<NotRequired>> Ivory
  BorderColor<<NotRequired>> Lavender
}

'Enumerations

'enum DATA_CATEGORY {
'  GENERAL
'  BIOMETRIC
'  GENETIC
'  HEALTH
'  ETHNIC_ORIGIN
'  RACIAL_ORIGIN
'  POLITICAL_AFFILIATION
'  CRIMINAL_OFFENSE
'  RELIGIOUS_BELIEF
'  TRADE_UNION_MEMBERSHIP
'  SEXUAL_ORIENTATION
'}

'Associations

FilingSystem --|> InformationSystem
PaymentInfo -- Consent : "requires" >
TechnicalMeasures -- RequestPayment : protects >
DataSubject -- PaymentInfo : provides >
Tollgate -- InformationSystem : implements >
Tollgate -- Processor
Consent -- ConsentAgreement : manifests >
'DataBreach -- DataBreachNotification : manifests >
'DPIA -- DPIAReport : manifests >
RequestPayment -- ProcessingLog : manifests >
PaymentInfo -- SpecialPurpose
Purpose -- Consent
Tollgate --|> DataHandler
Processor --|> DataHandler
Bank --|> DataHandler
ThirdParty --|> DataHandler
DataHandler -- PaymentInfo : receives >
InformationSystem -- RequestPayment : performs >
InformationSystem -- TechnicalMeasures : implements >

@enduml